name: Build and Publish Container Image

on:
  push:
    branches:
    - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        context: git
        images: |
          ghcr.io/{{ github.repository_owner }}/express-app
        tags: |
          type=sha
          type=raw,value=latest

    - name: docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: setup docker build
      uses: docker/setup-buildx-action@v3

    - name: build and publish container image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
